[package]
name = "outbound-mysql"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
mysql_async = { version = "0.30.0", default-features = false }
flate2 = { version = "1.0.17", features = ["zlib-ng"], default-features = false }
mysql_common = { version = "0.29.1", default-features = false }
spin-core = { path = "../core" }
spin-world = { path = "../world" }
tokio = { version = "1", features = [ "rt-multi-thread" ] }
tracing = { version = "0.1", features = [ "log" ] }
url = "2.3.1"
