spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A Spin Rust application demonstrating the variables sdk."
name = "spin-variables-rust"
trigger = { type = "http" }
version = "0.1.0"

[variables]
object = { default = "teapot" }
dotenv = { default = "should-be-replaced" }

[[component]]
id = "spin_variales_rust"
source = "target/wasm32-wasi/release/spin_variables_example.wasm"
[component.trigger]
route = "/..."
[component.config]
message = "I'm a {{object}}"
dotenv = "{{dotenv}}"
[component.build]
command = "cargo build --target wasm32-wasi --release"
