spin_manifest_version = 2

[application]
name = "spin-config-tinygo"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple Spin application written in (Tiny)Go."
version = "1.0.0"

[variables]
object = { default = "teapot" }

[[trigger.http]]
route = "/..."
component = "spin-config-tinygo"

[component.spin-config-tinygo]
source = "main.wasm"

[component.spin-config-tinygo.variables]
message = "I'm a {{object}}"

[component.spin-config-tinygo.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
