[package]
    name    = "spin-cli"
    version = "0.1.0"
    edition = "2021"
    authors = [ "Radu Matei <radu.matei@fermyon.com>" ]

[dependencies]
    anyhow         = "1.0"
    async-trait    = "0.1"
    bytes          = "1.1"
    comfy-table    = "4.1"
    env_logger     = "0.9"
    futures        = "0.3"
    hippo-client   = { path = "crates/hippo-client" }
    log            = { version = "0.4", default-features = false }
    semver         = "1.0"
    serde          = { version = "1.0", features = [ "derive" ] }
    spin-engine    = { path = "crates/engine" }
    spin-http      = { path = "crates/http" }
    spin-templates = { path = "crates/templates" }
    structopt      = "0.3"
    tokio          = { version = "1.11", features = [ "full" ] }
    toml           = "0.5"
    wact-client    = { git = "https://github.com/fermyon/wact", rev = "955eb8fe4ace52e3bd9994c1199f5ec5b9ce7895" }
    wact-core      = { git = "https://github.com/fermyon/wact", rev = "955eb8fe4ace52e3bd9994c1199f5ec5b9ce7895" }

[workspace]
    members = [ "crates/engine", "crates/hippo-client", "crates/http", "crates/templates" ]

[[bin]]
    name = "spin"
    path = "src/bin/spin.rs"
