[package]
    name    = "spin-cli"
    version = "0.1.0"
    edition = "2021"
    authors = ["Radu Matei <radu.matei@fermyon.com>"]


[dependencies]
    anyhow            = "1.0"
    async-trait       = "0.1"
    bytes             = "1.1"
    comfy-table       = "4.1"
    env_logger        = "0.9"
    fermyon-templates = { path = "crates/templates" }
    futures           = "0.3"
    log               = { version = "0.4", default-features = false }
    serde             = { version = "1.0", features = ["derive"] }
    structopt         = "0.3"
    tokio             = { version = "1.11", features = ["full"] }
    toml              = "0.5"


[workspace]
    members = ["crates/templates", "crates/engine"]


[[bin]]
    name = "spin"
    path = "src/bin/spin.rs"
