version: "3.9"

services:
  mysql:
    image: ${MYSQL_IMAGE:-mysql:8.0.22}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: spin
      MYSQL_DATABASE: spin_dev
      MYSQL_USER: spin
      MYSQL_PASSWORD: spin

  redis:
    image: ${REDIS_IMAGE:-redis:7.0.8-alpine3.17}
    ports:
      - "6379:6379"
    restart: always

  e2e-tests:
    depends_on:
      - mysql
      - redis
    image: spin-e2e-tests
    entrypoint: cargo test spinup_tests --features new-e2e-tests --no-fail-fast -- --nocapture

volumes:
  db_data: {}
