[package]
    name    = "spin-redis"
    version = "0.1.0"
    edition = "2021"
    authors = [ "Radu Matei <radu.matei@fermyon.com>" ]

[dependencies]
    anyhow               = "1.0"
    async-trait          = "0.1"
    env_logger           = "0.9"
    futures              = "0.3"
    log                  = { version = "0.4", default-features = false }
    serde                = { version = "1.0", features = [ "derive" ] }
    spin-engine          = { path = "../engine" }
    redis                = { version = "0.21", features = [ "tokio-comp" ] }
    tokio                = { version = "1.14", features = [ "full" ] }
    wit-bindgen-rust     = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "2e654dc82b7f9331719ba617a36ed5967b2aecb0" }
    wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "2e654dc82b7f9331719ba617a36ed5967b2aecb0" }
    wasi-common          = "0.33"
    wasmtime             = "0.33"
    wasmtime-wasi        = "0.33"
