[package]
name = "spin-config"
version = "0.1.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[dependencies]
anyhow = "1.0"
async-trait = "0.1.52"
itertools = "0.10.3"
serde = { version = "1.0", features = [ "derive" ] }
tokio = "1.16.1"
