[package]
name = "outbound-pg"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
spin-core = { path = "../core" }
tokio = { version = "1", features = [ "rt-multi-thread" ] }
tokio-postgres = { version = "0.7.7" }
tracing = { version = "0.1", features = [ "log" ] }
wit-bindgen-wasmtime = { workspace = true }