[package]
name = "outbound-http"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow  = "1.0"
http = "0.2"
reqwest = { version = "0.11", features = ["gzip"] }
spin-app = { path = "../app" }
spin-core = { path = "../core" }
spin-world = { path = "../world" }
terminal = { path = "../terminal" }
tracing = { workspace = true }
url = "2.2.1"
