[package]
name = "outbound-http"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow  = "1.0"
http = "0.2"
reqwest = "0.11"
spin-app = { path = "../app" }
spin-core = { path = "../core" }
tracing = { version = "0.1", features = [ "log" ] }
url = "2.2.1"
wit-bindgen-wasmtime = { workspace = true }
