[package]
name = "spin-common"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
sha2 = "0.10"
tokio = { version = "1", features = ["rt", "time"] }

[dev-dependencies]
tempfile = "3.5"