spin_manifest_version = "1"
authors = ["Adam Reese <adam@reese.io>"]
description = ""
name = "tinygo-sqlite"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "tinygo-sqlite"
source = "main.wasm"
allowed_http_hosts = []
sqlite_databases = ["default"]
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
