[package]
name = "spin-engine"
version = "0.1.0"
edition = "2021"
authors = [ "Radu Matei <radu.matei@fermyon.com>" ]

[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.51"
bindle = "0.8.0"
bytes = "1.1.0"
dirs = "4.0"
fs_extra = "1.2.0"
futures = "0.3.17"
git2 = "0.13"
glob = "0.3.0"
lazy_static = "1.4.0"
regex = "1.5.4"
serde = { version = "1.0.130", features = [ "derive" ] }
sha2 = "0.10.1"
spin-config = { path = "../config" }
structopt = "0.3.23"
tempfile = "3.3.0"
tokio = { version = "1.10.0", features = [ "fs" ] }
toml = "0.5.8"
tracing = { version = "0.1", features = [ "log" ] }
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3.7", features = [ "env-filter" ] }
wasi-common = "0.34"
wasmtime = "0.34"
wasmtime-wasi = "0.34"
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "e9c7c0a3405845cecd3fe06f3c20ab413302fc73" }

[dev-dependencies]
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "e9c7c0a3405845cecd3fe06f3c20ab413302fc73" }
