[package]
    name    = "spin-engine"
    version = "0.1.0"
    edition = "2021"
    authors = [ "Radu Matei <radu.matei@fermyon.com>" ]

[dependencies]
    anyhow                          = "1.0.44"
    async-trait                     = "0.1.51"
    bytes                           = "1.1.0"
    dirs                            = "4.0"
    env_logger                      = "0.9.0"
    fs_extra                        = "1.2.0"
    futures                         = "0.3.17"
    git2                            = "0.13"
    log                             = { version = "0.4.14", default-features = false }
    serde                           = { version = "1.0.130", features = [ "derive" ] }
    structopt                       = "0.3.23"
    tokio                           = { version = "1.10.0", features = [ "fs" ] }
    toml                            = "0.5.8"
    tracing                         = { version = "0.1", features = [ "log" ] }
    wasi-common                     = "0.31"
    wasi-experimental-http-wasmtime = "0.7.0"
    wasmtime                        = "0.31"
    wasmtime-wasi                   = "0.31"
    wit-bindgen-rust                = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "32e63116d469d8046727fae3c1333a7d35d0c5d3" }

[dev-dependencies]
    wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "32e63116d469d8046727fae3c1333a7d35d0c5d3" }
