[package]
    name    = "spinhelloworld"
    version = "0.1.0"
    edition = "2021"

[lib]
    crate-type = [ "cdylib" ]

[dependencies]
    # The Wact dependency generates bindings that simplify working with interfaces.
    wact = { git = "https://github.com/fermyon/wact" }

[workspace]


# Metadata about this component.
[package.metadata.component]
    name = "spinhelloworld"

# This component implements the fermyon/http interface.
[package.metadata.component.exports]
    fermyon-http = { reference = "fermyon/http", version = "0.1.0" }
