[package]
    name    = "spinhelloworld"
    version = "0.1.0"
    edition = "2021"

[lib]
    crate-type = [ "cdylib" ]

[dependencies]
    # The wit-bindgen-rust dependency generates bindings for interfaces.
    wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "2e654dc82b7f9331719ba617a36ed5967b2aecb0" }

[workspace]


# Metadata about this component.
[package.metadata.component]
    name = "spinhelloworld"