apiVersion = "0.1.0"
authors = ["Radu Matei <radu@fermyon.com>"]
description = "A simple application that returns hello and goodbye."
name = "spin-hello-world"
trigger = {type = "http", base = "/test"}
version = "1.0.0"

[[component]]
id = "hello"
source = "target/wasm32-wasi/release/spinhelloworld.wasm"
middleware = ["hello-middleware"]
[component.trigger]
route = "/hello"

[[component]]
id = "hello-middleware"
source = "target/wasm32-wasi/release/spinhelloworld.wasm"
