spin_manifest_version = 2

[application]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[[trigger.http]]
route = "{{http-path}}"
component = "{{project-name | kebab_case}}"
executor = { type = "wagi"}

[component.{{project-name | kebab_case}}]
files = [ { source = "./src", destination = "/" } ]
allowed_http_hosts = []
[component.{{project-name | kebab_case}}.source]
url = "https://github.com/vmware-labs/webassembly-language-runtimes/releases/download/php%2F7.4.32%2B20221124-2159d1c/php-cgi-7.4.32.speed-optimized.wasm"
digest = "sha256:511720698dee56134ed8a08a87131d33c3ea8a64b6726cd6710d624bca4ceb6c"
