spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "rust-outbound-redis-example"
trigger = { type = "http" }
version = "0.1.0"

[[component]]
environment = { REDIS_ADDRESS = "redis://127.0.0.1:6379", REDIS_CHANNEL = "messages" }
id = "outbound-redis"
source = "target/wasm32-wasi/release/rust_outbound_redis.wasm"
allowed_redis_hosts = ["redis://127.0.0.1:6379"]
[component.trigger]
route = "/publish"
[component.build]
command = "cargo build --target wasm32-wasi --release"
