[package]
name = "sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-component-bindings = "0.4.0"
futures = "0.3.29"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:sqlite"

[package.metadata.component.dependencies]

[package.metadata.component.target]
dependencies."wasi:http" = { path = "../../wit/deps/http" }
dependencies."wasi:io" = { path = "../../wit/deps/io" }
dependencies."fermyon:spin" = { path = "../../wit" }
