[package]
    name    = "hippo-client"
    version = "0.1.0"
    edition = "2021"
    authors = [ "Ivan Towlson <ivan.towlson@fermyon.com>", "Radu Matei <radu.matei@fermyon.com>" ]

[dependencies]
    anyhow       = "^1.0"
    reqwest      = { version = "0.11", features = [ "stream" ] }
    semver       = { version = "0.11", features = [ "serde" ] }
    serde        = { version = "1.0", features = [ "derive" ] }
    serde_json   = "1.0.72"
    thiserror    = "^1.0"
    tokio        = { version = "1.0", features = [ "full" ] }
    tokio-util   = { version = "0.6", features = [ "io" ] }
    tokio-stream = { version = "0.1", features = [ "fs" ] }
    tracing      = { version = "0.1", features = [ "log" ] }
    url          = "^2.2"
    uuid         = "0.8.2"
