spin_version = "1"
authors = ["Mossaka <jiazho@microsoft.com>"]
description = "A simple component for HTTP CloudEvents abuse protection."
name = "cloudevents-abuse-protection"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "validate"
source = "target/wasm32-wasi/release/cloudevents_abuse_protection.wasm"
allowed_http_hosts = ["*"]
[component.trigger]
route = "/"
[component.build]
command = "cargo build --target wasm32-wasi --release"
